version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: --bind-address=0.0.0.0
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - app-net

  php-backend:
    build: ./backend
    container_name: php-backend
    depends_on:
      - mysql
    volumes:
      - images-storage:/var/www/html/images
    networks:
      - app-net

  internal-api:
    build: ./internal
    container_name: internal-api
    expose:
      - "1234"
    networks:
      - app-net

  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - app-net

  reverse-proxy:
    image: nginx:stable-alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - php-backend
    networks:
      - app-net

volumes:
  mysql-data:
  frontend-static:
  images-storage: 

networks:
  app-net:
    driver: bridge
